name: CI/CD pour Insta-lite - front-end

on:
  push:
    branches: [develop,main,integration]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Installation des dépendances
        run: npm install

      - name: Build de l'application Angular
        run: ng build --prod

      - name: Build Docker images
        run: doc
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Déploiement de l'application
        run: |
          # Vous pouvez exécuter ici les commandes nécessaires pour déployer votre application Angular.
          # Cela peut inclure le transfert des fichiers d'artefact vers le serveur de déploiement,
          # le redémarrage du serveur web, etc.
          # Assurez-vous d'installer les dépendances nécessaires et de configurer votre environnement de déploiement.

      # Vous pouvez ajouter d'autres étapes pour des tâches spécifiques à votre pipeline de déploiement.

